require 'dotenv'
Dotenv.load

default_platform(:ios)

platform :ios do
  desc "dev testflight upload"
  lane :upload_dev_testflight do
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_filepath: ENV["KEY_FILEPATH"],
    )
    # アプリの配布をする。
    # ipaに指定されているpathのipaファイルを使用して、testflightに配布をしている。
    pilot(
      ipa: "../build/ios/ipa/Dev sample fastlane.ipa",
      api_key: api_key,
    )
  end

  desc "testflight upload"
  lane :upload_testflight do
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_filepath: ENV["KEY_FILEPATH"],
    )
    # アプリの配布をする。
    # ipaに指定されているpathのipaファイルを使用して、testflightに配布をしている。
    pilot(
      ipa: "../build/ios/ipa/Sample fastlane.ipa",
      api_key: api_key,
    )
  end
end
